import { GoogleGenAI } from '@google/genai';
import { NextRequest, NextResponse } from 'next/server';
import {
  createFallbackProfile,
  normalizeGeneratedProfile,
  sanitizePublicName,
  type AssetPresence,
  type TobyworldActivity,
  type TobyworldProfileInput,
} from '@/lib/tobyworld-profile';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type RateLimitEntry = {
  count: number;
  resetAt: number;
};

const rateLimitStore = new Map<string, RateLimitEntry>();
const MAX_REQUESTS_PER_WINDOW = 8;
const WINDOW_MS = 10 * 60 * 1000;

const responseSchema = {
  type: 'object',
  properties: {
    archetype: { type: 'string', description: 'A lore archetype, max 48 characters.' },
    title: { type: 'string', description: 'A poetic title, max 72 characters.' },
    narrative: { type: 'string', description: 'A warm two-sentence profile, max 260 characters.' },
    castText: { type: 'string', description: 'A short cast, max 280 characters.' },
    tweetText: { type: 'string', description: 'A short post for X, max 260 characters.' },
    accent: { type: 'string', enum: ['blue', 'red', 'green', 'gold'] },
  },
  required: ['archetype', 'title', 'narrative', 'castText', 'tweetText', 'accent'],
  additionalProperties: false,
} as const;

export async function POST(request: NextRequest) {
  const input = await parseProfileInput(request);

  if (!input) {
    return NextResponse.json({ error: 'Invalid profile signal.' }, { status: 400 });
  }

  const authSubject = await getVerifiedFarcasterSubject(request);
  const key = authSubject ? `fid:${authSubject}` : `ip:${getClientIp(request)}`;

  if (!takeRateLimitSlot(key)) {
    return NextResponse.json(
      { error: 'The lore engine is resting. Try again in a few minutes.' },
      { status: 429, headers: { 'Retry-After': '600' } },
    );
  }

  const fallback = createFallbackProfile(input);
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    return NextResponse.json({ profile: fallback, source: 'fallback' }, noStoreHeaders());
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: process.env.GEMINI_PROFILE_MODEL ?? 'gemini-2.5-flash-lite',
      contents: buildPrompt(input),
      config: {
        systemInstruction: [
          'You write short, playful, mythic Tobyworld identity profiles.',
          'Use only the supplied categorical signals. Never infer a quantity, balance, dollar value, wallet address, transaction value, market value, token price, eligibility, reward, APY, APR, return, profit, or financial outcome.',
          'The user may hold $TOBY, $PATIENCE, and $TABOSHI, but never state or imply how much of any asset they hold.',
          'The writing is lore-first, friendly, and non-financial. Avoid investment advice and calls to buy or sell.',
          'Use no hashtags. Do not state that the profile was generated by AI.',
          'The cast and X post must stand alone, be celebratory without bragging, and contain no numbers that could look like holdings.',
        ].join(' '),
        responseMimeType: 'application/json',
        responseSchema,
        temperature: 1,
        maxOutputTokens: 360,
      },
    });

    const parsed = JSON.parse(response.text || '{}') as unknown;
    const profile = normalizeGeneratedProfile(parsed, fallback);

    return NextResponse.json({ profile, source: 'gemini' }, noStoreHeaders());
  } catch {
    return NextResponse.json({ profile: fallback, source: 'fallback' }, noStoreHeaders());
  }
}

function buildPrompt(input: TobyworldProfileInput): string {
  return JSON.stringify({
    publicDisplayName: input.displayName,
    publicHandle: input.handle,
    assetSignals: input.assets,
    atlasActivity: input.activity,
    task:
      'Create one compact profile identity and two share messages from the categorical signals. Never use amounts, numbers, balances, prices, or financial language.',
  });
}

async function parseProfileInput(request: NextRequest): Promise<TobyworldProfileInput | null> {
  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return null;
  }

  if (!body || typeof body !== 'object') return null;
  const candidate = body as Record<string, unknown>;
  const assets = candidate.assets as Record<string, unknown> | undefined;
  const activity = candidate.activity as Record<string, unknown> | undefined;

  if (!assets || !activity) return null;

  const assetState = (value: unknown): AssetPresence | null =>
    value === 'held' || value === 'not_detected' ? value : null;

  const toby = assetState(assets.toby);
  const patience = assetState(assets.patience);
  const taboshi = assetState(assets.taboshi);

  if (!toby || !patience || !taboshi) return null;

  const gardenLeavesRaw = Number(activity.gardenLeaves);
  const gardenLeaves = [0, 1, 2, 3].includes(gardenLeavesRaw)
    ? (gardenLeavesRaw as TobyworldActivity['gardenLeaves'])
    : null;

  if (gardenLeaves === null) return null;

  return {
    displayName: sanitizePublicName(candidate.displayName),
    handle: sanitizePublicName(candidate.handle),
    assets: { toby, patience, taboshi },
    activity: {
      stillWaterAwakened: Boolean(activity.stillWaterAwakened),
      gardenLeaves,
      satoAwake: Boolean(activity.satoAwake),
      lorelandSeen: Boolean(activity.lorelandSeen),
    },
  };
}

async function getVerifiedFarcasterSubject(request: NextRequest): Promise<string | null> {
  const authorization = request.headers.get('authorization');
  if (!authorization?.startsWith('Bearer ')) return null;

  try {
    const { createClient } = await import('@farcaster/quick-auth');
    const token = authorization.slice('Bearer '.length);
    const client = createClient();
    const domain = process.env.FARCASTER_AUTH_DOMAIN ?? request.nextUrl.hostname;
    const payload = await client.verifyJwt({ token, domain });
    return String(payload.sub);
  } catch {
    return null;
  }
}

function getClientIp(request: NextRequest): string {
  const forwarded = request.headers.get('x-forwarded-for');
  return forwarded?.split(',')[0]?.trim() || request.headers.get('x-real-ip') || 'unknown';
}

function takeRateLimitSlot(key: string): boolean {
  const now = Date.now();
  const existing = rateLimitStore.get(key);

  if (!existing || now >= existing.resetAt) {
    rateLimitStore.set(key, { count: 1, resetAt: now + WINDOW_MS });
    return true;
  }

  if (existing.count >= MAX_REQUESTS_PER_WINDOW) return false;

  existing.count += 1;
  return true;
}

function noStoreHeaders() {
  return {
    headers: {
      'Cache-Control': 'no-store, max-age=0',
    },
  };
}
